usb_cam:
  ros__parameters:
    video_device: "/dev/video0"
    framerate: 10.0        # The absolute sweet spot for mobile robotics
    image_width: 640
    image_height: 480
    pixel_format: "yuyv2rgb"   # Zero-CPU decoding
    av_device_format: "YUV422P"
    camera_name: "ov5693_camera"
    frame_id: "camera_link_optical"
    
    # --- Performance Locks ---
    auto_white_balance: false # Locked to prevent CPU spikes
    white_balance: 4000
    autoexposure: false       # Locked for consistent frame timing
    exposure: 100
    autofocus: false          # Locked to protect odometry
    focus: -1