costmap:
  ros__parameters:
    update_frequency: 2.0
    publish_frequency: 2.0
    global_frame: map
    robot_base_frame: base_link
    use_sim_time: true
    
    # --- ROBOT FOOTPRINT (Based on CAD Calculations) ---
    # Front: 0.3078m (Covers nose/casters)
    # Back: -0.097m (Covers rear wheels)
    # Width: 0.486m (Total width) -> +/- 0.243m
    # Format: [[x1, y1], [x2, y2], [x3, y3], [x4, y4]]
    footprint: "[[0.3078, 0.243], [0.3078, -0.243], [-0.097, -0.243], [-0.097, 0.243]]"
    
    # Extra safety buffer around the defined rectangle
    footprint_padding: 0.02

    resolution: 0.05
    track_unknown_space: true
    
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
    
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      map_topic: /map
      subscribe_to_updates: true
    
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: True
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        clearing: True
        marking: True
        data_type: "LaserScan"
        raytrace_max_range: 3.0
        raytrace_min_range: 0.0
        obstacle_max_range: 2.5
        obstacle_min_range: 0.0
    
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      cost_scaling_factor: 3.0
      inflation_radius: 0.55
      
    always_send_full_costmap: True