twist_mux:
  ros__parameters:
    use_stamped: false
    topics:
      joystick:
        topic   : joy_vel
        timeout : 0.5
        priority: 99
      keyboard: 
        topic   : key_vel
        timeout : 0.5
        priority: 90
      voice:
        topic   : cmd_vel_voice
        timeout : 0.5
        priority: 85
      tracker:
        topic   : cmd_vel_tracker
        timeout : 0.5
        priority: 50
      navigation: 
        topic   : cmd_vel
        timeout : 0.5
        priority: 10